DROP TABLE IF EXISTS CARTITEM;
CREATE TABLE CARTITEM
  (
     id         BIGINT NOT NULL,
     userid     BIGINT NOT NULL,
     itemid     BIGINT NOT NULL,
     itemname   VARCHAR(255),
     quantity   BIGINT NOT NULL,
     PRIMARY KEY (id)
  );

DROP SEQUENCE IF EXISTS CartItemSeq;
CREATE SEQUENCE CartItemSeq INCREMENT 1 MINVALUE 1
    MAXVALUE 9223372036854775807
    START 1
    CACHE 1;